In [3]:
import numpy as np
import torch
from torch import nn


# 학습에 사용할 CPU나 GPU 장치를 얻습니다.
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

# 모델을 정의합니다.
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [15]:
import numpy as np
import torch

# 중첩 list를 지정
t = torch.tensor([[1, 2], [3, 4.]])
print(t)

# device를 지정하면 GPU로 Tensor를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]])

# dtype을 사용해 데이터형을 지정해 Tensor를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]], dtype=torch.float64)

# 0부터 9까지의 수치로 초기화된 1차원 Tensor
t = torch.arange(0, 10)
print('0부터 9까지의 수치로 초기화된 1차원 Tensor :', t)
#모든 값이 0인 100 x 10 의 Tensor를
#작성해서 to메서드로 GPU에 전송
t = torch.zeros(100, 10).to(device)

# 정규 난수로 100 x 10의 Tensor를 작성
t = torch.randn(100, 10)
print(t)
# Tensor의 shape은 size 메서드로 취득 가능
t.size()

tensor([[1., 2.],
        [3., 4.]])
0부터 9까지의 수치로 초기화된 1차원 Tensor : tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[ 1.1221e+00, -3.7848e-02, -2.6966e-01, -2.0691e-01, -1.8196e-02,
         -5.3912e-01,  5.2918e-01, -7.4397e-01, -1.6465e+00, -2.7490e-01],
        [ 1.6706e+00, -6.8109e-01, -4.7055e-01, -7.9269e-01,  1.2167e+00,
         -4.2326e-01, -1.1555e+00, -5.8885e-01, -3.6033e-01, -4.2231e-01],
        [-1.6998e+00,  1.5496e+00, -1.1256e+00, -3.3543e-01,  9.2675e-01,
          7.4566e-01,  9.4800e-01,  1.4540e+00, -1.2695e-01,  3.9902e-01],
        [ 3.2554e-01,  1.2180e+00,  2.4588e-02,  4.4699e-01, -1.9127e+00,
          1.5835e+00, -3.0028e-01, -4.7849e-03, -1.2559e+00, -5.6896e-01],
        [-3.9041e-02,  7.3487e-01, -5.2201e-01,  7.6771e-01, -1.7426e+00,
         -7.6852e-01, -8.6330e-01,  1.3976e-01,  1.9307e+00, -2.6089e-01],
        [ 1.1684e+00, -3.5243e-01,  9.1609e-01, -1.2555e+00,  4.1881e-01,
          9.0958e-01, -7.5861e-01, -1.6959e-01, -2.5089e-01, -1.5856e+00],

torch.Size([100, 10])

In [9]:
# numpy 메서드를 사용해 ndarray로 변환
t = torch.tensor([[1, 2], [3, 4.]])
x = t.numpy()

# GPU上상의 Tensor는 cpu메서드로,
# CPU의 Tensor로 이동(변환)할 필요가 있다
t = torch.tensor([[1, 2], [3, 4.]], device="cpu")
x = t.to("cpu").numpy()

In [24]:
t = torch.tensor([[1,2,3], [4,5,6.]])
print(t)
# 스칼라 첨자 지정
t[0, 2]

# 슬라이스로 지정
t[:, :2]

# 리스트로 지정
t[:, [1,2]]

# 마스크 배열을 시용해서 3보다 큰 부분만 선택
t[t > 3]

# [0, 1]의 요소를 100으로 설정
t[0, 1] = 100

# 슬라이스를 사용한 일괄 대입
t[:, 1] = 200

# 마스크 배열을 사용해서 특정 조건의 요소만 치환
t[t > 10] = 20
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])


### 텐서 연산

In [31]:
# 길이 3인 벡터
v = torch.tensor([1, 2, 3.])
w = torch.tensor([0, 10, 20.])

# 2 × 3의 행렬
m = torch.tensor([[0, 1, 2], [100, 200, 300.]])

# 벡터와 스칼라의 덧셈
v2 = v + 10
print(v2)
# 자승도 같은 방식
v2 = v ** 2
print(v2)
# 동일 길이의 벡터 간 뺄쎔
z = v - w
print(z)
# 여러 가지 조합
u = 2 * v - w / 10 + 6.0

# 행렬과 스칼라
m2 = m * 2.0
print(m2)
# 행렬과 벡터
#(2, 3)인 행렬과 (3,)인 벡터이므로 브로드 캐스트가 작동
m3 = m + v
print(m3)
# 행렬 간 처리
m4 = m + m
print(m4)

tensor([11., 12., 13.])
tensor([1., 4., 9.])
tensor([  1.,  -8., -17.])
tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])
tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])
tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])
