In [3]:
import numpy as np
import torch
from torch import nn


# 학습에 사용할 CPU나 GPU 장치를 얻습니다.
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

# 모델을 정의합니다.
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [15]:
import numpy as np
import torch

# 중첩 list를 지정
t = torch.tensor([[1, 2], [3, 4.]])
print(t)

# device를 지정하면 GPU로 Tensor를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]])

# dtype을 사용해 데이터형을 지정해 Tensor를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]], dtype=torch.float64)

# 0부터 9까지의 수치로 초기화된 1차원 Tensor
t = torch.arange(0, 10)
print('0부터 9까지의 수치로 초기화된 1차원 Tensor :', t)
#모든 값이 0인 100 x 10 의 Tensor를
#작성해서 to메서드로 GPU에 전송
t = torch.zeros(100, 10).to(device)

# 정규 난수로 100 x 10의 Tensor를 작성
t = torch.randn(100, 10)
print(t)
# Tensor의 shape은 size 메서드로 취득 가능
t.size()

tensor([[1., 2.],
        [3., 4.]])
0부터 9까지의 수치로 초기화된 1차원 Tensor : tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[ 1.1221e+00, -3.7848e-02, -2.6966e-01, -2.0691e-01, -1.8196e-02,
         -5.3912e-01,  5.2918e-01, -7.4397e-01, -1.6465e+00, -2.7490e-01],
        [ 1.6706e+00, -6.8109e-01, -4.7055e-01, -7.9269e-01,  1.2167e+00,
         -4.2326e-01, -1.1555e+00, -5.8885e-01, -3.6033e-01, -4.2231e-01],
        [-1.6998e+00,  1.5496e+00, -1.1256e+00, -3.3543e-01,  9.2675e-01,
          7.4566e-01,  9.4800e-01,  1.4540e+00, -1.2695e-01,  3.9902e-01],
        [ 3.2554e-01,  1.2180e+00,  2.4588e-02,  4.4699e-01, -1.9127e+00,
          1.5835e+00, -3.0028e-01, -4.7849e-03, -1.2559e+00, -5.6896e-01],
        [-3.9041e-02,  7.3487e-01, -5.2201e-01,  7.6771e-01, -1.7426e+00,
         -7.6852e-01, -8.6330e-01,  1.3976e-01,  1.9307e+00, -2.6089e-01],
        [ 1.1684e+00, -3.5243e-01,  9.1609e-01, -1.2555e+00,  4.1881e-01,
          9.0958e-01, -7.5861e-01, -1.6959e-01, -2.5089e-01, -1.5856e+00],

torch.Size([100, 10])

In [9]:
# numpy 메서드를 사용해 ndarray로 변환
t = torch.tensor([[1, 2], [3, 4.]])
x = t.numpy()

# GPU上상의 Tensor는 cpu메서드로,
# CPU의 Tensor로 이동(변환)할 필요가 있다
t = torch.tensor([[1, 2], [3, 4.]], device="cpu")
x = t.to("cpu").numpy()

In [24]:
t = torch.tensor([[1,2,3], [4,5,6.]])
print(t)
# 스칼라 첨자 지정
t[0, 2]

# 슬라이스로 지정
t[:, :2]

# 리스트로 지정
t[:, [1,2]]

# 마스크 배열을 시용해서 3보다 큰 부분만 선택
t[t > 3]

# [0, 1]의 요소를 100으로 설정
t[0, 1] = 100

# 슬라이스를 사용한 일괄 대입
t[:, 1] = 200

# 마스크 배열을 사용해서 특정 조건의 요소만 치환
t[t > 10] = 20
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])


### 텐서 연산

In [31]:
# 길이 3인 벡터
v = torch.tensor([1, 2, 3.])
w = torch.tensor([0, 10, 20.])

# 2 × 3의 행렬
m = torch.tensor([[0, 1, 2], [100, 200, 300.]])

# 벡터와 스칼라의 덧셈ㅠㅡ


v2 = v + 10
print(v2)
# 자승도 같은 방식
v2 = v ** 2
print(v2)
# 동일 길이의 벡터 간 뺄쎔
z = v - w
print(z)
# 여러 가지 조합
u = 2 * v - w / 10 + 6.0

# 행렬과 스칼라
m2 = m * 2.0
print(m2)
# 행렬과 벡터
#(2, 3)인 행렬과 (3,)인 벡터이므로 브로드 캐스트가 작동
m3 = m + v
print(m3)
# 행렬 간 처리
m4 = m + m
print(m4)

tensor([11., 12., 13.])
tensor([1., 4., 9.])
tensor([  1.,  -8., -17.])
tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])
tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])
tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])


### 수학함수

In [33]:
# 100 × 10의 테스트 데이터 생성
X = torch.randn(100, 10)

# 수학 함수를 포함하는 수식
y = X * 2 + torch.abs(X)
# 평균치 구하기
m = torch.mean(X)
# 함수가 아닌 메서드로도 사용할 수 있다
m = X.mean()
# 집계 결과는 0차원의 Tensor로 item 메서드를 사용해서
# 값을 추출할 수 있다
m_value = m.item()
# 집계는 차원을 지정할 수도 있다. 다음은 행 방향으로 집계해서,
# 열 단위로 평균값을 계산한다
m2 = X.mean(0)

In [47]:
# 100 × 10의 테스트 데이터 생성
X = torch.randn(100, 10)

# 수학 함수를 포함하는 수식
y = X * 2 + torch.abs(X)

# 평균치 구하기
m = torch.mean(X)

# 함수가 아닌 메서드로도 사용할 수 있다
m = X.mean()

# 집계 결과는 0차원의 Tensor로 item 메서드를 사용해서
# 값을 추출할 수 있다
m_value = m.item()
# 집계는 차원을 지정할 수도 있다. 다음은 행 방향으로 집계해서,
# 열 단위로 평균값을 계산한다
m2 = X.mean(0)
print(m2)

tensor([-0.0154,  0.0739, -0.0139, -0.1652,  0.0426, -0.0563, -0.0519, -0.0907,
         0.0195, -0.0593])


In [50]:
x1 = torch.tensor([[1, 2], [3, 4.]]) # 2×2
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]]) # 2×3
print(x1)
# 2×2를 4×1로 보여준다
x1.view(4, 1)
# -1는 나머지 차원을 나타내며 한 번만 사용할 수 있다
# 아래 예에선 -1을 사용하면 자동으로 4가 된다
x1.view(1, -1)

# 2×3을 전치해서 3×2로 만든다
x2.t()

# dim=1로 결합하면 2×5의 Tensor를 만든다
torch.cat([x1, x2], dim=1)

# HWC을 CHW로 변환
# 64×32×3의 데이터가 100개
hwc_img_data = torch.rand(100, 64, 32, 3)
chw_img_data = hwc_img_data.transpose(1, 2).transpose(1, 3)
print(hwc_img_data)

tensor([[1., 2.],
        [3., 4.]])
tensor([[[[0.9386, 0.4543, 0.3103],
          [0.7685, 0.1030, 0.7407],
          [0.8389, 0.2973, 0.6551],
          ...,
          [0.0984, 0.5865, 0.7414],
          [0.4089, 0.0808, 0.1609],
          [0.9655, 0.9396, 0.3837]],

         [[0.6321, 0.7779, 0.3406],
          [0.7746, 0.1210, 0.1503],
          [0.0717, 0.1494, 0.9978],
          ...,
          [0.9769, 0.8027, 0.1325],
          [0.6213, 0.6906, 0.0078],
          [0.2428, 0.0579, 0.4071]],

         [[0.4055, 0.0506, 0.7641],
          [0.4419, 0.4499, 0.4001],
          [0.6010, 0.8475, 0.6883],
          ...,
          [0.3657, 0.1748, 0.8274],
          [0.8796, 0.7974, 0.4483],
          [0.5645, 0.8756, 0.2575]],

         ...,

         [[0.2698, 0.3053, 0.8843],
          [0.1600, 0.8530, 0.1264],
          [0.8479, 0.1621, 0.3756],
          ...,
          [0.5200, 0.2561, 0.1422],
          [0.3840, 0.8210, 0.7126],
          [0.9051, 0.1370, 0.7706]],

         [[0.391

In [58]:
m = torch.randn(100, 10)
v = torch.randn(10)

# 내적
d = torch.dot(v, v)
print(d)
# 100 × 10의 행렬과 길이 10인 벡터의 곱
# 결과는 길이 100인 벡터
v2 = torch.mv(m, v)

# 행렬곱
m2 = torch.mm(m.t(), m)
print(m2)
print(m2.size())
# 특이값 분해
u, s, v = torch.svd(m)
print(u)
print(s)
print(v)

tensor(9.7566)
tensor([[ 1.2126e+02, -1.5620e+01,  2.9058e+00,  2.1998e+01, -1.6861e+00,
         -1.1164e+00, -1.2083e+00,  1.1249e+00, -1.2893e+01,  6.5908e+00],
        [-1.5620e+01,  1.2034e+02,  7.8235e+00,  5.7380e-01, -1.3622e+00,
         -7.1131e+00, -4.7419e+00, -3.8730e+00, -1.4011e+01, -1.9176e+01],
        [ 2.9058e+00,  7.8235e+00,  1.0637e+02,  1.1258e+01, -9.4452e+00,
         -2.9839e+00, -5.2028e+00, -6.0081e+00, -3.8956e-02,  9.8804e+00],
        [ 2.1998e+01,  5.7380e-01,  1.1258e+01,  1.0459e+02, -9.5713e+00,
         -4.6281e+00, -1.0508e+01, -2.1949e+00,  1.8054e+01,  1.2886e+01],
        [-1.6861e+00, -1.3622e+00, -9.4452e+00, -9.5713e+00,  9.0321e+01,
          4.4276e-01,  8.0517e+00, -6.9878e+00, -3.8567e+00,  3.7387e+00],
        [-1.1164e+00, -7.1131e+00, -2.9839e+00, -4.6281e+00,  4.4276e-01,
          9.9056e+01,  8.3838e+00,  5.2787e+00,  3.7617e+00, -1.7579e+01],
        [-1.2083e+00, -4.7419e+00, -5.2028e+00, -1.0508e+01,  8.0517e+00,
          8.3838e