In [1]:
# coding: utf-8
import numpy as np


class Sigmoid:
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))


class Affine:
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out


class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 가중치와 편향 초기화
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 계층 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 모든 가중치를 리스트에 모은다.
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x


x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(s)
 

[[ 1.46864629  0.12529523  0.3637941 ]
 [ 1.34174689 -0.34402171  1.58816782]
 [ 1.57618365  0.32500131  0.26479337]
 [ 1.51841755  0.17395761  0.53405705]
 [ 1.73292739  0.80466979 -0.92004834]
 [ 1.51701002  0.22602407  0.23927846]
 [ 1.43484226  0.0501249   0.46295811]
 [ 1.39662094 -0.0650884   0.64351692]
 [ 1.67002061  0.61023694 -0.55538379]
 [ 1.58927765  0.39305499 -0.01395011]]
