In [2]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out


class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 가중치와 편향 초기화
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 계층 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 모든 가중치를 리스트에 모은다.
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x


x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(s)
 


[[-0.87876628 -1.17007336  0.08856928]
 [-1.0046811  -1.11560256  0.02138698]
 [-2.54939874 -0.68640314 -0.76568493]
 [-1.96393041 -0.68900796 -0.49121246]
 [-1.1923848  -1.03091515 -0.11807905]
 [-0.91349405 -1.14317216  0.05034028]
 [-1.02002601 -1.12410923  0.04533868]
 [-2.15416289 -0.60343198 -0.70053793]
 [-1.00945417 -1.22449503  0.2099484 ]
 [-1.44874436 -1.26777389  0.2514016 ]]
