In [1]:
import numpy as np

In [2]:
a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [3]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [4]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


오버플로우 문제를 주의해야함

In [5]:
def softmax(a) :
  c = np.max(a)
  exp_a = np.exp(a - c) # 오버플로우에 대한 대책
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y

In [6]:
softmax(a)

array([0.01821127, 0.24519181, 0.73659691])