In [3]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out

    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        np.add.at(dW, self.idx, dout)
        return None

In [12]:
import numpy as np
A = np.arange(24).reshape(8, 3)

B = np.arange(12).reshape(4, 3)

idx = np.array([0, 0, 3, 5])

In [14]:
print('idx :', idx)
print('A :', A)
print('B :', B)


idx : [0 0 3 5]
A : [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
B : [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [15]:
np.add.at(A, idx, B)
A

array([[ 3,  6,  9],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [15, 17, 19],
       [12, 13, 14],
       [24, 26, 28],
       [18, 19, 20],
       [21, 22, 23]])